### ISSUE TITLE
Color argument out of order when len(col) == len(values)

### ISSUE THREAD

**Issue by bow** [mgymrek/pybeeswarm#5]
Hi @mgymrek,

I was playing around with the swarm plots (looks great by the way, thanks :) ). I noticed that when trying to color each point individually, the color always seem out of place (i.e. it colors the wrong point).

This small code snippet, which tries to color the highest value differently, produces the error:

```python
from beeswarm import *
import matplotlib.pyplot as plt
import numpy as np
d1 = np.random.normal(size=100)

max_d1 = max(d1)
d1_colors = ["grey" if x != max_d1 else "red" for x in d1]

bs, ax = beeswarm([d1], method="swarm", labels=["sample 1"], col=d1_colors)
```
Looking deeper into the code, I saw that this line seems to be responsible: https://github.com/mgymrek/pybeeswarm/blob/master/beeswarm/beeswarm.py#L210

The sort makes the `values` list out of sync with the `col` list.

Any chance of a fix coming :)?

P.S. I'm on Python 3.4, Linux, running Matplotlib 1.4.3

**Comment by mgymrek** [comment]
Hi @bow,
Thanks for pointing this problem out! The problem was not that particular line, but was due indeed to the data frame being sorted, making it out of sync with the function that called it and assumed the output is returned in the original order. [This commit](https://github.com/mgymrek/pybeeswarm/commit/c604a5231594d471bdd3e0c7d3242f275a50d338) should fix it. Let me know if this solves your issue.

**Comment by bow** [comment]
Hi @mgymrek,

This fixes the issue indeed. Thanks :)!
